import type { Metadata } from "next";
import { Vazirmatn, Inter } from "next/font/google";
import "./globals.css";
import { RootProvider } from "@/components/providers/root-provider";
import { Toaster } from "@/components/ui/sonner";

const vazir = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazir",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Roxai - Enterprise AI Presentation",
  description: "Generated by Roxai Platform",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazir.variable} ${inter.variable} font-sans antialiased`}
      >
        <RootProvider>
          {children}
          <Toaster
            richColors
            position="top-center"
            toastOptions={{ style: { fontFamily: vazir.style.fontFamily } }}
          />
        </RootProvider>
      </body>
    </html>
  );
}
