/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserListItemEmail } from './adminUserListItemEmail';
import type { AdminUserListItemMobile } from './adminUserListItemMobile';
import type { AdminUserListItemFirstName } from './adminUserListItemFirstName';
import type { AdminUserListItemLastName } from './adminUserListItemLastName';
import type { AdminUserListItemAvatarUrl } from './adminUserListItemAvatarUrl';
import type { UserRole } from './userRole';

export interface AdminUserListItem {
  id: string;
  email?: AdminUserListItemEmail;
  mobile?: AdminUserListItemMobile;
  first_name?: AdminUserListItemFirstName;
  last_name?: AdminUserListItemLastName;
  avatar_url?: AdminUserListItemAvatarUrl;
  role: UserRole;
  /** Current wallet balance */
  credit?: number;
  is_active: boolean;
  is_verified: boolean;
  created_at: string;
}
