/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export type AdminListProjectsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
/**
 * Filter by User ID
 */
user_id?: string | null;
/**
 * Filter by Project Status
 */
status?: string | null;
};
