/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectStatus } from './projectStatus';
import type { AdminProjectListItemUserEmailOrMobile } from './adminProjectListItemUserEmailOrMobile';

export interface AdminProjectListItem {
  id: string;
  user_id: string;
  title: string;
  status: ProjectStatus;
  created_at: string;
  updated_at: string;
  user_email_or_mobile?: AdminProjectListItemUserEmailOrMobile;
}
