/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLogResponseItemTargetUserId } from './auditLogResponseItemTargetUserId';
import type { AuditLogResponseItemDetails } from './auditLogResponseItemDetails';
import type { AuditLogResponseItemReasonNote } from './auditLogResponseItemReasonNote';
import type { AuditLogResponseItemIpAddress } from './auditLogResponseItemIpAddress';

export interface AuditLogResponseItem {
  id: string;
  admin_id: string;
  target_user_id: AuditLogResponseItemTargetUserId;
  action: string;
  details: AuditLogResponseItemDetails;
  reason_note: AuditLogResponseItemReasonNote;
  ip_address?: AuditLogResponseItemIpAddress;
  created_at: string;
}
