/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface BatchActionRequest {
  project_ids: string[];
  /** @pattern ^(archive|delete)$ */
  action: string;
}
