/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export interface ChangeRoleRequest {
  target_user_id: string;
  new_role: UserRole;
  /**
   * Reason for promotion/demotion
   * @minLength 5
   */
  reason_note: string;
}
