/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordRequest {
  /**
   * رمز عبور فعلی
   * @minLength 8
   */
  old_password: string;
  /**
   * رمز عبور جدید
   * @minLength 8
   */
  new_password: string;
}
