/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface ConfirmIdentifierChange {
  new_identifier: string;
  /**
   * @minLength 4
   * @maxLength 6
   */
  code: string;
}
