/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface CreditAdjustmentRequest {
  target_user_id: string;
  /** Amount to add (positive) or remove (negative) */
  amount: number;
  /**
   * Mandatory audit note
   * @minLength 5
   */
  reason_note: string;
}
