/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';
import type { FeatureFlagUpdateRequestDescription } from './featureFlagUpdateRequestDescription';

export interface FeatureFlagUpdateRequest {
  /** وضعیت کلی سوئیچ */
  is_enabled: boolean;
  /** لیست شناسه کاربرانی که این ویژگی برایشان فعال است (Whitelisting) */
  target_users?: string[];
  /** لیست نقش‌هایی که به این ویژگی دسترسی دارند */
  target_roles?: UserRole[];
  description?: FeatureFlagUpdateRequestDescription;
}
