/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { FeatureFlagResponseDescription } from './featureFlagResponseDescription';
import type { UserRole } from './userRole';

export interface FeatureFlagResponse {
  id: string;
  key: string;
  description: FeatureFlagResponseDescription;
  is_enabled: boolean;
  target_users: string[];
  target_roles: UserRole[];
  updated_at: string;
}
