/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface GoogleLoginRequest {
  /** Google ID Token received from Frontend */
  id_token: string;
}
