/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export type IdentifyResponseDetectedType = typeof IdentifyResponseDetectedType[keyof typeof IdentifyResponseDetectedType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentifyResponseDetectedType = {
  email: 'email',
  mobile: 'mobile',
} as const;
