/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifyResponseDetectedType } from './identifyResponseDetectedType';
import type { IdentifyResponseNextStep } from './identifyResponseNextStep';

export interface IdentifyResponse {
  exists: boolean;
  detected_type: IdentifyResponseDetectedType;
  next_step: IdentifyResponseNextStep;
  masked_identifier: string;
}
