/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export type IdentifyResponseNextStep = typeof IdentifyResponseNextStep[keyof typeof IdentifyResponseNextStep];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentifyResponseNextStep = {
  password: 'password',
  otp: 'otp',
  register: 'register',
} as const;
