/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface ImpersonateRequest {
  target_user_id: string;
  /**
   * Reason for impersonation access
   * @minLength 3
   */
  reason: string;
}
