/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectStatus } from './projectStatus';
import type { SortField } from './sortField';
import type { SortOrder } from './sortOrder';

export type ListProjectsParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 50
 */
page_size?: number;
search?: string | null;
status?: ProjectStatus | null;
/**
 * Filter by specific folder ID
 */
folder_id?: string | null;
/**
 * If true, returns only projects NOT in any folder
 */
is_root?: boolean;
sort_by?: SortField;
sort_order?: SortOrder;
};
