/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export type ListUsersApiV1AdminUsersGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
/**
 * Search by email, mobile, name or ID
 */
query?: string | null;
/**
 * Filter by user role
 */
role?: UserRole | null;
};
