/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLogResponseItem } from './auditLogResponseItem';

export interface PaginatedAuditLogResponse {
  items: AuditLogResponseItem[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}
