/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminProjectListItem } from './adminProjectListItem';

export interface PaginatedProjectResponse {
  items: AdminProjectListItem[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}
