/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterRequestFirstName } from './registerRequestFirstName';
import type { RegisterRequestLastName } from './registerRequestLastName';

export interface RegisterRequest {
  /** Token received from verify-otp endpoint */
  verification_token: string;
  /** @minLength 8 */
  password: string;
  first_name?: RegisterRequestFirstName;
  last_name?: RegisterRequestLastName;
}
