/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export type SoftDeleteUserParams = {
/**
 * Audit reason for deletion
 * @minLength 3
 */
reason: string;
};
