/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export type SortField = typeof SortField[keyof typeof SortField];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortField = {
  created_at: 'created_at',
  updated_at: 'updated_at',
  title: 'title',
  status: 'status',
} as const;
