/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface SystemHealthResponse {
  database_status: string;
  total_users: number;
  active_users_24h: number;
  pending_jobs_count: number;
  system_load: string;
}
