/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProfileRequestFirstName } from './updateProfileRequestFirstName';
import type { UpdateProfileRequestLastName } from './updateProfileRequestLastName';
import type { UpdateProfileRequestAvatarUrl } from './updateProfileRequestAvatarUrl';
import type { UpdateProfileRequestEmail } from './updateProfileRequestEmail';
import type { UpdateProfileRequestMobile } from './updateProfileRequestMobile';

export interface UpdateProfileRequest {
  first_name?: UpdateProfileRequestFirstName;
  last_name?: UpdateProfileRequestLastName;
  avatar_url?: UpdateProfileRequestAvatarUrl;
  email?: UpdateProfileRequestEmail;
  mobile?: UpdateProfileRequestMobile;
}
