/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateProjectRequestTitle } from './updateProjectRequestTitle';
import type { UpdateProjectRequestFolderId } from './updateProjectRequestFolderId';

export interface UpdateProjectRequest {
  title?: UpdateProjectRequestTitle;
  folder_id?: UpdateProjectRequestFolderId;
}
