/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import type { UserShortInfoEmail } from './userShortInfoEmail';
import type { UserShortInfoMobile } from './userShortInfoMobile';
import type { UserShortInfoFirstName } from './userShortInfoFirstName';
import type { UserShortInfoLastName } from './userShortInfoLastName';
import type { UserShortInfoAvatarUrl } from './userShortInfoAvatarUrl';

export interface UserShortInfo {
  id: string;
  email?: UserShortInfoEmail;
  mobile?: UserShortInfoMobile;
  first_name?: UserShortInfoFirstName;
  last_name?: UserShortInfoLastName;
  avatar_url?: UserShortInfoAvatarUrl;
  role: string;
  credit?: number;
}
