/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

export interface UserStatusChangeRequest {
  target_user_id: string;
  /** True to activate/unban, False to ban/block */
  is_active: boolean;
  /**
   * Mandatory audit note for status change
   * @minLength 5
   */
  reason_note: string;
}
