/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Action to take next
 */
export type VerifyOtpResponseAction = typeof VerifyOtpResponseAction[keyof typeof VerifyOtpResponseAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifyOtpResponseAction = {
  login: 'login',
  register: 'register',
} as const;
