/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BatchActionRequest,
  CreateProjectRequest,
  HTTPValidationError,
  ListProjectsParams,
  ProjectListResponse,
  ProjectResponse,
  UpdateProjectRequest
} from '.././model';

import { customInstance } from '.././custom-instance';
import type { ErrorType } from '.././custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get list of projects.
- Use `folder_id` to see inside a folder.
- Use `is_root=True` to see top-level files only.
- Use neither to see ALL files (flat view).
 * @summary List Projects
 */
export const listProjects = (
    params?: ListProjectsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectListResponse>(
      {url: `/api/v1/projects/`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListProjectsQueryKey = (params?: ListProjectsParams,) => {
    return [
    `/api/v1/projects/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListProjectsQueryOptions = <TData = Awaited<ReturnType<typeof listProjects>>, TError = ErrorType<HTTPValidationError>>(params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListProjectsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProjects>>> = ({ signal }) => listProjects(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof listProjects>>>
export type ListProjectsQueryError = ErrorType<HTTPValidationError>


export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listProjects>>,
          TError,
          Awaited<ReturnType<typeof listProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Projects
 */

export function useListProjects<TData = Awaited<ReturnType<typeof listProjects>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listProjects>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListProjectsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create Project
 */
export const createProject = (
    createProjectRequest: CreateProjectRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectResponse>(
      {url: `/api/v1/projects/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProjectRequest, signal
    },
      options);
    }
  


export const getCreateProjectMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: CreateProjectRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: CreateProjectRequest}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {data: CreateProjectRequest}> = (props) => {
          const {data} = props ?? {};

          return  createProject(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = CreateProjectRequest
    export type CreateProjectMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Project
 */
export const useCreateProject = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{data: CreateProjectRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {data: CreateProjectRequest},
        TContext
      > => {

      const mutationOptions = getCreateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Update Project
 */
export const updateProject = (
    projectId: string,
    updateProjectRequest: UpdateProjectRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ProjectResponse>(
      {url: `/api/v1/projects/${projectId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateProjectRequest
    },
      options);
    }
  


export const getUpdateProjectMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: string;data: UpdateProjectRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: string;data: UpdateProjectRequest}, TContext> => {

const mutationKey = ['updateProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProject>>, {projectId: string;data: UpdateProjectRequest}> = (props) => {
          const {projectId,data} = props ?? {};

          return  updateProject(projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>
    export type UpdateProjectMutationBody = UpdateProjectRequest
    export type UpdateProjectMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Project
 */
export const useUpdateProject = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: string;data: UpdateProjectRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProject>>,
        TError,
        {projectId: string;data: UpdateProjectRequest},
        TContext
      > => {

      const mutationOptions = getUpdateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Archive Project
 */
export const archiveProject = (
    projectId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/projects/${projectId}`, method: 'DELETE'
    },
      options);
    }
  


export const getArchiveProjectMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveProject>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof archiveProject>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['archiveProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveProject>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  archiveProject(projectId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ArchiveProjectMutationResult = NonNullable<Awaited<ReturnType<typeof archiveProject>>>
    
    export type ArchiveProjectMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Archive Project
 */
export const useArchiveProject = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveProject>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveProject>>,
        TError,
        {projectId: string},
        TContext
      > => {

      const mutationOptions = getArchiveProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Duplicate Project
 */
export const duplicateProject = (
    projectId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProjectResponse>(
      {url: `/api/v1/projects/${projectId}/duplicate`, method: 'POST', signal
    },
      options);
    }
  


export const getDuplicateProjectMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateProject>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof duplicateProject>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['duplicateProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof duplicateProject>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  duplicateProject(projectId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DuplicateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof duplicateProject>>>
    
    export type DuplicateProjectMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Duplicate Project
 */
export const useDuplicateProject = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof duplicateProject>>, TError,{projectId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof duplicateProject>>,
        TError,
        {projectId: string},
        TContext
      > => {

      const mutationOptions = getDuplicateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Batch Projects Action
 */
export const batchProjectsAction = (
    batchActionRequest: BatchActionRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/projects/batch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: batchActionRequest, signal
    },
      options);
    }
  


export const getBatchProjectsActionMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchProjectsAction>>, TError,{data: BatchActionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof batchProjectsAction>>, TError,{data: BatchActionRequest}, TContext> => {

const mutationKey = ['batchProjectsAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof batchProjectsAction>>, {data: BatchActionRequest}> = (props) => {
          const {data} = props ?? {};

          return  batchProjectsAction(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BatchProjectsActionMutationResult = NonNullable<Awaited<ReturnType<typeof batchProjectsAction>>>
    export type BatchProjectsActionMutationBody = BatchActionRequest
    export type BatchProjectsActionMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Batch Projects Action
 */
export const useBatchProjectsAction = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchProjectsAction>>, TError,{data: BatchActionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof batchProjectsAction>>,
        TError,
        {data: BatchActionRequest},
        TContext
      > => {

      const mutationOptions = getBatchProjectsActionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    