/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreditAdjustmentRequest,
  HTTPValidationError,
  ImpersonateRequest,
  ImpersonateResponse,
  ListUsersParams,
  PaginatedUserResponse
} from '.././model';

import { customInstance } from '.././custom-instance';
import type { ErrorType } from '.././custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * دریافت لیست کاربران با قابلیت جستجو و فیلتر.
 * @summary List Users
 */
export const listUsers = (
    params?: ListUsersParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PaginatedUserResponse>(
      {url: `/api/v1/admin/users`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getListUsersQueryKey = (params?: ListUsersParams,) => {
    return [
    `/api/v1/admin/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<HTTPValidationError>>(params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = ErrorType<HTTPValidationError>


export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Users
 */

export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Adjust User Credit
 */
export const adjustUserCredit = (
    creditAdjustmentRequest: CreditAdjustmentRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/admin/ledger/adjust`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: creditAdjustmentRequest, signal
    },
      options);
    }
  


export const getAdjustUserCreditMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adjustUserCredit>>, TError,{data: CreditAdjustmentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adjustUserCredit>>, TError,{data: CreditAdjustmentRequest}, TContext> => {

const mutationKey = ['adjustUserCredit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adjustUserCredit>>, {data: CreditAdjustmentRequest}> = (props) => {
          const {data} = props ?? {};

          return  adjustUserCredit(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdjustUserCreditMutationResult = NonNullable<Awaited<ReturnType<typeof adjustUserCredit>>>
    export type AdjustUserCreditMutationBody = CreditAdjustmentRequest
    export type AdjustUserCreditMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Adjust User Credit
 */
export const useAdjustUserCredit = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adjustUserCredit>>, TError,{data: CreditAdjustmentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adjustUserCredit>>,
        TError,
        {data: CreditAdjustmentRequest},
        TContext
      > => {

      const mutationOptions = getAdjustUserCreditMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * تولید یک توکن موقت برای ورود به حساب کاربر بدون نیاز به پسورد.
 * @summary Impersonate User
 */
export const impersonateUser = (
    impersonateRequest: ImpersonateRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ImpersonateResponse>(
      {url: `/api/v1/admin/auth/impersonate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: impersonateRequest, signal
    },
      options);
    }
  


export const getImpersonateUserMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof impersonateUser>>, TError,{data: ImpersonateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof impersonateUser>>, TError,{data: ImpersonateRequest}, TContext> => {

const mutationKey = ['impersonateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof impersonateUser>>, {data: ImpersonateRequest}> = (props) => {
          const {data} = props ?? {};

          return  impersonateUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ImpersonateUserMutationResult = NonNullable<Awaited<ReturnType<typeof impersonateUser>>>
    export type ImpersonateUserMutationBody = ImpersonateRequest
    export type ImpersonateUserMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Impersonate User
 */
export const useImpersonateUser = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof impersonateUser>>, TError,{data: ImpersonateRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof impersonateUser>>,
        TError,
        {data: ImpersonateRequest},
        TContext
      > => {

      const mutationOptions = getImpersonateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    