from typing import Protocol, Optional
import uuid
from backend.src.domain.entities.user import User

class IUserRepository(Protocol):
    async def get_by_email(self, email: str) -> Optional[User]: ...
    async def get_by_mobile(self, mobile: str) -> Optional[User]: ...
    async def get_by_id(self, user_id: uuid.UUID) -> Optional[User]: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...

class ISmsService(Protocol):
    async def send_otp(self, mobile: str, code: str) -> bool: ...

class IEmailService(Protocol):
    async def send_otp(self, email: str, code: str) -> bool: ...

