"""add_credit_column_and_indexes

Revision ID: b895a4a14e63
Revises: 04867c7ef42a
Create Date: 2026-01-31 14:32:02.904314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b895a4a14e63'
down_revision: Union[str, None] = '04867c7ef42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('ix_users_email_mobile', 'users', ['email', 'mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_mobile', table_name='users')
    op.drop_column('users', 'credit')
    # ### end Alembic commands ###