/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Roxai API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GoogleLoginRequest,
  HTTPValidationError,
  IdentifyRequest,
  IdentifyResponse,
  LoginRequest,
  RegisterRequest,
  SendOtpRequest,
  TokenResponse,
  VerifyOtpRequest,
  VerifyOtpResponse
} from '.././model';





/**
 * @summary Identify User
 */
export const identifyUser = (
    identifyRequest: IdentifyRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IdentifyResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/api/v1/auth/identify`,
      identifyRequest,options
    );
  }



export const getIdentifyUserMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof identifyUser>>, TError,{data: IdentifyRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof identifyUser>>, TError,{data: IdentifyRequest}, TContext> => {

const mutationKey = ['identifyUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof identifyUser>>, {data: IdentifyRequest}> = (props) => {
          const {data} = props ?? {};

          return  identifyUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type IdentifyUserMutationResult = NonNullable<Awaited<ReturnType<typeof identifyUser>>>
    export type IdentifyUserMutationBody = IdentifyRequest
    export type IdentifyUserMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Identify User
 */
export const useIdentifyUser = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof identifyUser>>, TError,{data: IdentifyRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof identifyUser>>,
        TError,
        {data: IdentifyRequest},
        TContext
      > => {

      const mutationOptions = getIdentifyUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * ارسال کد تایید پیامکی
 * @summary Send Otp
 */
export const sendOtp = (
    sendOtpRequest: SendOtpRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/api/v1/auth/otp/send`,
      sendOtpRequest,options
    );
  }



export const getSendOtpMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendOtp>>, TError,{data: SendOtpRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof sendOtp>>, TError,{data: SendOtpRequest}, TContext> => {

const mutationKey = ['sendOtp'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendOtp>>, {data: SendOtpRequest}> = (props) => {
          const {data} = props ?? {};

          return  sendOtp(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendOtpMutationResult = NonNullable<Awaited<ReturnType<typeof sendOtp>>>
    export type SendOtpMutationBody = SendOtpRequest
    export type SendOtpMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Send Otp
 */
export const useSendOtp = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendOtp>>, TError,{data: SendOtpRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendOtp>>,
        TError,
        {data: SendOtpRequest},
        TContext
      > => {

      const mutationOptions = getSendOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * بررسی کد تایید و دریافت توکن ثبت‌نام
 * @summary Verify Otp
 */
export const verifyOtp = (
    verifyOtpRequest: VerifyOtpRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<VerifyOtpResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/api/v1/auth/otp/verify`,
      verifyOtpRequest,options
    );
  }



export const getVerifyOtpMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyOtp>>, TError,{data: VerifyOtpRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof verifyOtp>>, TError,{data: VerifyOtpRequest}, TContext> => {

const mutationKey = ['verifyOtp'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyOtp>>, {data: VerifyOtpRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyOtp(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyOtpMutationResult = NonNullable<Awaited<ReturnType<typeof verifyOtp>>>
    export type VerifyOtpMutationBody = VerifyOtpRequest
    export type VerifyOtpMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Verify Otp
 */
export const useVerifyOtp = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyOtp>>, TError,{data: VerifyOtpRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyOtp>>,
        TError,
        {data: VerifyOtpRequest},
        TContext
      > => {

      const mutationOptions = getVerifyOtpMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * ثبت‌نام نهایی و دریافت توکن ورود
 * @summary Register User
 */
export const registerUser = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TokenResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/api/v1/auth/register`,
      registerRequest,options
    );
  }



export const getRegisterUserMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = RegisterRequest
    export type RegisterUserMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Register User
 */
export const useRegisterUser = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {

      const mutationOptions = getRegisterUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * ورود با رمز عبور
 * @summary Login User
 */
export const loginUser = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TokenResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/api/v1/auth/login`,
      loginRequest,options
    );
  }



export const getLoginUserMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = LoginRequest
    export type LoginUserMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Login User
 */
export const useLoginUser = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * ورود یا ثبت‌نام با حساب گوگل (OAuth)
 * @summary Login With Google
 */
export const loginWithGoogle = (
    googleLoginRequest: GoogleLoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TokenResponse>> => {
    
    
    return axios.post(
      `http://127.0.0.1:8000/api/v1/auth/google`,
      googleLoginRequest,options
    );
  }



export const getLoginWithGoogleMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithGoogle>>, TError,{data: GoogleLoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginWithGoogle>>, TError,{data: GoogleLoginRequest}, TContext> => {

const mutationKey = ['loginWithGoogle'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginWithGoogle>>, {data: GoogleLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginWithGoogle(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginWithGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof loginWithGoogle>>>
    export type LoginWithGoogleMutationBody = GoogleLoginRequest
    export type LoginWithGoogleMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Login With Google
 */
export const useLoginWithGoogle = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginWithGoogle>>, TError,{data: GoogleLoginRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginWithGoogle>>,
        TError,
        {data: GoogleLoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginWithGoogleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    